#!/usr/bin/env node
/*
 * Gate for the Pinokio launcher scripts: no single DISPATCH may be long enough
 * to wedge Pinokio's shell.
 *
 * ---------------------------------------------------------------------------
 * WHY
 * ---------------------------------------------------------------------------
 * Pinokio 8.0.x hangs — one CPU core at 100%, no child process ever spawns,
 * the install dead until a force-quit — when a single command written to its
 * pty is too long.  @Morac2 bisected the ceiling in #50: a 764-char command
 * hangs, ~373 passes.  v3.6.2 adopted "no generated shell line over 350" from
 * that, and the issue was closed.
 *
 * It came back twice, from two different people:
 *   #50  @davidaircloud  "The individual lines are now short, but the joined
 *                         message generated by install.js is still 1,417
 *                         characters."  Moving that body into a .sh and
 *                         dispatching `bash ../x.sh` fixed his install.
 *   #56  @itrejomx       same stall before `uv venv`; fixed by splitting the
 *                         payload into smaller shell.run steps.
 *
 * The rule was right and the MEASUREMENT was wrong.  What Pinokio dispatches
 * is not "a line of the source" — it is one string per shell:
 *
 *   pinokiod/kernel/shells.js  launch()
 *       message is an ARRAY and no `chain` param  -> each element is launched
 *                                                    in its OWN shell (so an
 *                                                    array is already safe;
 *                                                    element size is what
 *                                                    counts)
 *       message is an ARRAY and `chain` is set    -> Shell.build() joins them
 *                                                    into ONE dispatch
 *       message is a STRING                       -> ONE dispatch, as-is
 *
 *   pinokiod/kernel/shell.js:1911
 *       this.ptyProcess.write(`${this.exec_cmd || this.cmd}${this.EOL}`)
 *       — one unchunked write, however big it is.  The same file's
 *         Shell.emit() (shell.js:665-711) chunks anything over 1024 chars into
 *         256-byte pieces with a 10 ms gap, so the kernel already knows large
 *         pty writes are unsafe; the shell.run path just doesn't do it.
 *
 * Every long payload in this repo is written `[ ... ].join("\n")` — a STRING,
 * deliberately, so an if/else runs in one shell.  Those are exactly the
 * dispatches nobody was measuring: the venv step's source lines were all under
 * 110 chars and it dispatched 1,417 in one go.
 *
 * A local pty probe (bash --noprofile --norc, Pinokio's own shell/args, one
 * unchunked os.write) completes a 1,475-byte payload fine, so this is not a
 * kernel tty limit — it is Pinokio's terminal layer, and dispatch size is the
 * only lever we have from this side.
 *
 * ---------------------------------------------------------------------------
 * THE RULE
 * ---------------------------------------------------------------------------
 * Every dispatch <= 500 chars, measured the way @Morac2 measured it: the
 * message content, before Pinokio prepends its conda activation.  Anything
 * bigger belongs in scripts/pinokio/ and becomes one short `bash ...` line.
 *
 * Run: node scripts/check_pinokio_scripts.js      exit 0 = PASS
 */
const path = require("path")

// The evidence, and nothing beyond it:
//   proven to HANG   764 (@Morac2, #50) and 1,417 (@davidaircloud, #50 / #56)
//   proven to WORK   ~373 (@Morac2's own bisection) and every dispatch this
//                    repo has shipped, the largest of which is 498 (update.js
//                    step 11, in every release since it landed)
// 500 sits just above the proven-working band and well under the proven-hanging
// one. 350 would be the ideal target but would fail six dispatches that
// demonstrably work for everyone today, and churning those in a hotfix buys
// risk, not safety. Tighten toward 350 in a feature release, not here.
const MAX_DISPATCH = 500

const SCRIPTS = [
  "install.js", "update.js", "install_h3.js", "install_qwen.js",
  "install_sharp.js", "download_q8.js", "download_upscaler.js",
  "start.js", "reset.js", "pinokio.js",
]

// Shell.build()'s array delimiters (kernel/shell.js:932), used only when a
// `chain` param is present — which is what makes an array ONE dispatch.
function chainDelimiter(chain) {
  if (chain === "*") return " ; "
  if (chain === "|") return " || "
  return " && "
}

// What kernel/shells.js launch() actually writes to the pty, as a list.
function dispatches(params) {
  const m = params.message
  if (!m) return []
  if (typeof m === "string") return [m]
  if (Array.isArray(m)) {
    if (params.chain) {
      return [m.filter((x) => x && !/^\s+$/.test(x))
        .map(String).join(chainDelimiter(params.chain))]
    }
    return m.filter(Boolean).map(String)   // one shell per element
  }
  return [String(m)]
}

function* walk(node, trail) {
  if (Array.isArray(node)) {
    for (let i = 0; i < node.length; i++) yield* walk(node[i], trail.concat(i))
    return
  }
  if (!node || typeof node !== "object") return
  if (node.method === "shell.run" && node.params) yield { step: node, trail }
  for (const k of Object.keys(node)) {
    if (k === "method" || k === "params") continue
    yield* walk(node[k], trail.concat(k))
  }
}

const root = path.resolve(__dirname, "..")
const failures = []
let steps = 0
let count = 0
let worst = 0
let worstWhere = ""

for (const name of SCRIPTS) {
  let mod
  try {
    mod = require(path.join(root, name))
  } catch (e) {
    failures.push(`${name}: FAILED TO LOAD — ${e.message}`)
    continue
  }
  // pinokio.js exports an ASYNC menu() that needs a live kernel + info object,
  // and its entries only reference the other scripts — it dispatches nothing
  // itself. Loading it (above) is the check that applies to it.
  const trees = []
  if (mod && mod.run) trees.push(mod.run)
  for (const tree of trees) {
    for (const { step, trail } of walk(tree, [])) {
      steps++
      const list = dispatches(step.params)
      list.forEach((cmd, k) => {
        count++
        const where = `${name} [${trail.join(".")}]` +
          (list.length > 1 ? ` element ${k}` : "")
        if (cmd.length > worst) { worst = cmd.length; worstWhere = where }
        if (cmd.length > MAX_DISPATCH) {
          failures.push(`${where}: DISPATCH ${cmd.length} > ${MAX_DISPATCH}` +
            ` — move it into scripts/pinokio/ and dispatch one short line` +
            `\n      starts: ${cmd.slice(0, 72).replace(/\n/g, "\\n")}`)
        }
      })
    }
  }
}

console.log(`${count} dispatches across ${steps} shell.run steps in ${SCRIPTS.length} scripts`)
console.log(`worst dispatch: ${worst} chars (limit ${MAX_DISPATCH})  ${worstWhere}`)
if (failures.length) {
  console.log("")
  for (const f of failures) console.log("FAIL  " + f)
  console.log(`\nRESULT: FAIL (${failures.length})`)
  process.exit(1)
}
console.log("\nRESULT: PASS")
